name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Build project
      run: npm run build
      
    - name: Run linting
      run: npm run lint
      
  #  - name: Run unit tests
   #   run: npm test
      
    - name: Run Playwright tests
      run: npm run test:e2e
      
    - name: Generate HTML report from JSON
      if: always()
      run: |
        mkdir -p test-report
        # Create HTML summary from test result JSONs
        node scripts/generate-html-report.js
        # Copy JSON files to report directory for reference
        cp test-results/testSummary.json test-report/
        cp test-results/testFailures.json test-report/
        # Add index.html that shows the report
        cp scripts/report-template.html test-report/index.html
        
    - name: Upload test results JSON
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-json
        path: test-results/
        retention-days: 30

    - name: Upload test HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: test-report/
        retention-days: 30
        
    - name: Publish Test Report
      if: always() && github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-report
        destination_dir: reports/${{ github.run_number }}
        keep_files: true

    - name: Publish Latest Test Report
      if: always() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-report
        destination_dir: reports/latest
        keep_files: true

  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build package
      run: npm run build
        
    - name: Check version and publish
      run: |
        # Get version from package.json
        PKG_VERSION=$(node -p "require('./package.json').version")
        
        # Check if this version already exists on npm
        if npm view playwright-ci-reporter@$PKG_VERSION version &> /dev/null; then
          echo "Version $PKG_VERSION already exists on npm, skipping publish"
        else
          echo "Publishing version $PKG_VERSION to npm"
          npm publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
